# fallback 

DEMO_RECIPES = [
    {"label": "Grilled Chicken Salad", "url": "", "image": "", "servings": 1,
     "ingredients": ["4 oz chicken breast", "2 cups mixed greens", "1/2 cup cherry tomatoes", "1/4 cup feta cheese", "2 tbsp olive oil dressing"],
     "health_labels": ["Gluten-Free", "Peanut-Free"], "calories": 420, "protein": 38.5, "fat": 22.0, "carbs": 12.0},
    {"label": "Overnight Oats with Berries", "url": "", "image": "", "servings": 1,
     "ingredients": ["1/2 cup rolled oats", "1 cup almond milk", "1/4 cup blueberries", "1 tbsp chia seeds", "1 tsp honey"],
     "health_labels": ["Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 350, "protein": 12.0, "fat": 8.5, "carbs": 58.0},
    {"label": "Salmon with Roasted Vegetables", "url": "", "image": "", "servings": 1,
     "ingredients": ["6 oz salmon fillet", "1 cup broccoli florets", "1/2 cup sweet potato cubes", "1 tbsp olive oil", "lemon juice"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Peanut-Free"], "calories": 510, "protein": 42.0, "fat": 24.0, "carbs": 30.0},
    {"label": "Turkey & Avocado Wrap", "url": "", "image": "", "servings": 1,
     "ingredients": ["3 oz sliced turkey breast", "1 whole wheat tortilla", "1/2 avocado", "lettuce", "tomato slices"],
     "health_labels": ["Peanut-Free", "Tree-Nut-Free"], "calories": 380, "protein": 28.0, "fat": 18.0, "carbs": 30.0},
    {"label": "Greek Yogurt Parfait", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 cup Greek yogurt", "1/4 cup granola", "1/2 cup mixed berries", "1 tbsp honey"],
     "health_labels": ["Peanut-Free", "Egg-Free"], "calories": 310, "protein": 22.0, "fat": 6.0, "carbs": 45.0},
    {"label": "Quinoa Buddha Bowl", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 cup cooked quinoa", "1/2 cup chickpeas", "1 cup roasted vegetables", "2 tbsp tahini dressing", "1/4 avocado"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 520, "protein": 18.0, "fat": 22.0, "carbs": 68.0},
    {"label": "Shrimp Stir-Fry", "url": "", "image": "", "servings": 1,
     "ingredients": ["5 oz shrimp", "1 cup mixed stir-fry vegetables", "2 tbsp soy sauce", "1 tsp sesame oil", "1 cup brown rice"],
     "health_labels": ["Dairy-Free", "Peanut-Free", "Egg-Free"], "calories": 460, "protein": 32.0, "fat": 10.0, "carbs": 60.0},
    {"label": "Mediterranean Chickpea Salad", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 can chickpeas", "1 cup cucumber", "1/2 cup cherry tomatoes", "1/4 cup red onion", "2 oz feta cheese", "2 tbsp olive oil"],
     "health_labels": ["Gluten-Free", "Egg-Free", "Peanut-Free"], "calories": 440, "protein": 20.0, "fat": 22.0, "carbs": 45.0},
    {"label": "Banana Protein Smoothie", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 banana", "1 scoop whey protein", "1 cup milk", "1 tbsp peanut butter", "ice cubes"],
     "health_labels": ["Egg-Free", "Gluten-Free"], "calories": 380, "protein": 32.0, "fat": 12.0, "carbs": 42.0},
    {"label": "Beef & Broccoli", "url": "", "image": "", "servings": 1,
     "ingredients": ["5 oz beef sirloin", "2 cups broccoli", "2 tbsp soy sauce", "1 tbsp cornstarch", "1 cup jasmine rice"],
     "health_labels": ["Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 550, "protein": 40.0, "fat": 16.0, "carbs": 58.0},
    {"label": "Egg & Veggie Scramble", "url": "", "image": "", "servings": 1,
     "ingredients": ["3 large eggs", "1/2 cup bell peppers", "1/4 cup onion", "1/4 cup spinach", "1 slice whole wheat toast"],
     "health_labels": ["Dairy-Free", "Peanut-Free", "Gluten-Free"], "calories": 320, "protein": 22.0, "fat": 18.0, "carbs": 16.0},
    {"label": "Lentil Soup", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 cup red lentils", "2 cups vegetable broth", "1/2 cup carrots", "1/2 cup celery", "1 tsp cumin"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 350, "protein": 24.0, "fat": 4.0, "carbs": 55.0},
    {"label": "Tuna Nicoise Salad", "url": "", "image": "", "servings": 1,
     "ingredients": ["4 oz canned tuna", "2 boiled eggs", "1 cup green beans", "1/2 cup potatoes", "2 tbsp vinaigrette"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Peanut-Free"], "calories": 430, "protein": 35.0, "fat": 18.0, "carbs": 30.0},
    {"label": "Chicken Burrito Bowl", "url": "", "image": "", "servings": 1,
     "ingredients": ["4 oz chicken thigh", "1/2 cup black beans", "1/2 cup brown rice", "1/4 cup salsa", "1/4 avocado", "lettuce"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Peanut-Free"], "calories": 520, "protein": 36.0, "fat": 16.0, "carbs": 56.0},
    {"label": "Spinach & Mushroom Omelette", "url": "", "image": "", "servings": 1,
     "ingredients": ["3 eggs", "1 cup spinach", "1/2 cup mushrooms", "1 oz goat cheese", "1 tsp olive oil"],
     "health_labels": ["Gluten-Free", "Peanut-Free"], "calories": 340, "protein": 26.0, "fat": 24.0, "carbs": 6.0},
    {"label": "Asian Noodle Soup", "url": "", "image": "", "servings": 1,
     "ingredients": ["2 oz rice noodles", "3 oz tofu", "2 cups chicken broth", "1 cup bok choy", "1 tsp ginger", "soy sauce"],
     "health_labels": ["Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 310, "protein": 16.0, "fat": 8.0, "carbs": 44.0},
    {"label": "Sweet Potato & Black Bean Tacos", "url": "", "image": "", "servings": 1,
     "ingredients": ["1 medium sweet potato", "1/2 cup black beans", "2 corn tortillas", "1/4 cup salsa", "lime juice"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 380, "protein": 14.0, "fat": 4.0, "carbs": 72.0},
    {"label": "Caprese Panini", "url": "", "image": "", "servings": 1,
     "ingredients": ["2 slices sourdough bread", "4 oz fresh mozzarella", "1 large tomato", "fresh basil leaves", "1 tbsp balsamic glaze"],
     "health_labels": ["Peanut-Free", "Tree-Nut-Free", "Egg-Free"], "calories": 450, "protein": 24.0, "fat": 20.0, "carbs": 42.0},
    {"label": "Mango Chicken Curry", "url": "", "image": "", "servings": 1,
     "ingredients": ["5 oz chicken breast", "1/2 cup mango chunks", "1/2 cup coconut milk", "1 cup basmati rice", "curry powder"],
     "health_labels": ["Gluten-Free", "Dairy-Free", "Egg-Free", "Peanut-Free"], "calories": 580, "protein": 38.0, "fat": 18.0, "carbs": 65.0},
    {"label": "Avocado Toast with Poached Egg", "url": "", "image": "", "servings": 1,
     "ingredients": ["2 slices whole grain bread", "1 avocado", "2 poached eggs", "red pepper flakes", "salt and pepper"],
     "health_labels": ["Dairy-Free", "Peanut-Free"], "calories": 410, "protein": 18.0, "fat": 26.0, "carbs": 32.0},
    {"label": "Pesto Pasta with Chicken", "url": "", "image": "", "servings": 1,
     "ingredients": ["2 oz whole wheat pasta", "4 oz grilled chicken", "2 tbsp pesto", "1/4 cup cherry tomatoes", "parmesan cheese"],
     "health_labels": ["Egg-Free", "Peanut-Free"], "calories": 520, "protein": 40.0, "fat": 20.0, "carbs": 42.0},
]
